config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :payments, path: '/pagamentos', except: [:show]
  resources :payment_categories, path: '/categorias', except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :payment_category
  belongs_to :payment_frequency
end

app/models/payment_category.rb
class PaymentCategory < ApplicationRecord
    validates :name, presence: true
end

app/models/payment_frequency.rb
class PaymentFrequency < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payment_categories_controller.rb
class PaymentCategoriesController < ApplicationController
  before_action :set_payment_category, only: [:show, :edit, :update, :destroy]

  def index
    @payment_categories = PaymentCategory.all
  end

  def show; end

  def new
    @payment_category = PaymentCategory.new
  end

  def create
    @payment_category = PaymentCategory.new(payment_category_params)
    @payment_category.save
    turbo_stream
  end

  def edit; end

  def update
    @payment_category.update(payment_category_params)
    turbo_stream
  end

  def destroy
    @payment_category.destroy
    turbo_stream
  end

  private
    def payment_category_params
      params.require(:payment_category).permit(:name)
    end

    def set_payment_category
      @payment_category = PaymentCategory.find(params[:id])
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show]

  def index
    @payments = Payment.all
  end

  def show; end

  private
  def set_payment
    @payment = Payment.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payment_categories_helper.rb
module PaymentCategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lemon&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main>
      <%= render partial: "shared/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/payment_categories/_categories.html.erb
<turbo_frame id="payment_categories_tag">
  <ul id="payments_categories" class="flex flex-col">
    <% if payment_categories.empty? %>
        <span class="text-gray-400">
          Nenhuma categoria cadastrada
        </span>
    <% else %>
      <% payment_categories.each do |payment_category| %>
        <%= render partial: "payment_category", locals: { payment_category: payment_category } %>
      <% end %>
    <% end %>
  </ul>
</turbo_frame>

app/views/payment_categories/_form.html.erb
<div class="flex flex-col gap-6">
  <%= form_with(model: payment_category, html: { :id => dom_id(payment_category, :form) }) do |form| %>
    <div class="flex flex-col gap-2">
      <div class="flex gap-4">
        <%= form.text_field :name, placeholder: "Ex.: Serviços", class: "w-full h-12 rounded" %>
        <%= form.submit "Cadastrar", title: "Salvar categoria", class: "bg-[#3155d2] hover:opacity-50 ease-in-out duration-200 disabled:bg-blue-100 text-white disabled:text-black cursor-pointer disabled:cursor-not-allowed h-12 rounded w-32" %>
      </div>

      <% if payment_category.errors.any? %>
        <span class="text-red-500">
          <%= payment_category.errors.full_messages_for(:name).join(',') %>
        </span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/payment_categories/_payment_category.html.erb
<li id="<%= dom_id(payment_category, :li) %>" class="border-b py-3">
  <%= turbo_frame_tag payment_category do %>
    <div class="flex items-center justify-between gap-4">
      <span><%= payment_category.name %></span>

      <div class="flex items-center gap-2">
        <form method="get" action="<%= edit_payment_category_path(payment_category.id) %>">
          <button title="Editar" class="h-10 w-10 bg-blue-300 text-white rounded-full hover:opacity-50 ease-in-out duration-200 flex items-center justify-center">
            <span class="material-symbols-outlined">edit</span>
          </button>
        </form>

        <form method="delete" action="<%= payment_category_path(payment_category.id) %>">
          <button title="Excluir" class="h-10 w-10 bg-red-400 text-white rounded-full hover:opacity-50 ease-in-out duration-200 flex items-center justify-center">
            <span class="material-symbols-outlined">delete</span>
          </button>
        </form>
      </div>
    </div>
  <% end %>
</li>

app/views/payment_categories/create.turbo_stream.erb
<% if @payment_category.errors.any? %>
  <%= turbo_stream.update "payment_category_form_tag" do %>
    <%= render partial: "form", locals: { payment_category: @payment_category } %>
  <% end %>
<% else %>
  <%= turbo_stream.update "payment_category_form_tag" do %>
    <%= render partial: "form", locals: { payment_category: PaymentCategory.new } %>
  <% end %>

  <%= turbo_stream.replace "payment_categories_tag" do %>
    <%= render partial: "categories", locals: { payment_categories: PaymentCategory.all } %>
  <% end %>
<% end %>

app/views/payment_categories/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@payment_category, :li) %>

app/views/payment_categories/edit.html.erb
<%= turbo_frame_tag @payment_category do %>
  <%= form_with(model: @payment_category, html: { :id => dom_id(@payment_category, :form) }) do |form| %>
    <div class="flex gap-4">
      <div class="flex flex-col gap-1 w-full">
        <%= form.text_field :name, id: "category-name-field", placeholder: "Ex.: Serviços", autofocus: 'true', class: "rounded" %>

        <% if @payment_category.errors.any? %>
          <span class="text-red-500">
            <%= @payment_category.errors.full_messages_for(:name).join(',') %>
          </span>
        <% end %>
      </div>

      <div class="flex items-center gap-4">
        <%= button_to "Cancelar", payment_categories_path, class: "flex justify-center items-center cursor-pointer h-8 rounded h-8" %>
        <%= form.submit "Salvar", title: "Salvar categoria", class: "bg-[#3155d2] disabled:bg-blue-100 text-white disabled:text-black cursor-pointer disabled:cursor-not-allowed h-10 px-4 rounded" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/payment_categories/index.html.erb
<turbo-frame id="payment-categories-modal-tag">
  <div class="fixed right-0 top-0 bottom-0">
    <div class="flex flex-col gap-8 w-full shadow-lg py-12 px-8 h-screen max-w-[500px] z-10 bg-white overflow-y-auto">
      <div class="flex flex-col gap-4 w-full">
        <div class="flex justify-between mb-6">
          <h1 class="text-xl font-bold">
            Categorias
          </h1>

          <form method="get" action="<%= payments_path %>">
            <button
              type="submit"
              title="Fechar"
              class="flex items-center justify-center w-6 h-6 rounded-full hover:opacity-50 ease-in-out duration-200"
            >
              <span class="material-symbols-outlined cursor-pointer">close</span>
            </button>
          </form>
        </div>

        <turbo-frame id="payment_category_form_tag" src="<%= new_payment_category_url %>">
        </turbo-frame>
      </div>

      <%= render partial: "categories", locals: { payment_categories: @payment_categories } %>
    </div>
  </div>
</turbo-frame>

app/views/payment_categories/new.html.erb
<turbo-frame id="payment_category_form_tag">
  <%= render partial: "form", locals: { payment_category: PaymentCategory.new } %>
</turbo-frame>

app/views/payment_categories/update.turbo_stream.erb
<% if @payment_category.errors.any? %>
  <%= turbo_stream.replace("payment_category_form_tag") do %>
    <%= render partial: "form", locals: { payment_category: @payment_category } %>
  <% end %>
<% else %>
  <%= turbo_stream.replace(dom_id(@payment_category, :li)) do %>
    <%= render partial: "payment_category", locals: { payment_category: @payment_category } %>
  <% end %>

  <%= turbo_stream.replace @payment_category do %>
    <%= render partial: "payment_category", locals: { payment_category: @payment_category } %>
  <% end %>
<% end %>

app/views/payments/index.html.erb
<section class="m-10">
  <%= link_to "Gerenciar categorias",
              payment_categories_path,
              class: "bg-blue-400 hover:opacity-50 ease-in-out duration-200 px-8 py-4 rounded text-white"
  %>

  <turbo-frame id="payment-categories-modal-tag">
  </turbo-frame>
</section>

app/views/shared/_navbar.html.erb
<nav class="bg-[#3155d2] h-20 px-4 flex items-center justify-between">
  <a href="/" class="text-white text-3xl font-lemon">
    Wallet
  </a>

  <div class="flex items-center">
    <button class="text-white text-base font-medium h-11 w-40 flex items-center justify-center rounded">
      Entrar
    </button>

    <button class="bg-white text-[#3155d2] text-base font-medium h-11 w-40 flex items-center justify-center rounded">
      Cadastre-se
    </button>
  </div>
</nav>